---
title: "Table 1: `r params$target_drug` Cohorts"
date: "`r Sys.Date()`"
output:
  html_document:
   toc: true
   toc_float: true
   toc_depth: 3
   theme: flatly
params:
  comp_vars:                       NULL
  comparator:                      NULL
  var_name_to_pretty:              NULL
  target_drug:                     "Semaglutide"
  all.data:                        NULL
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(tableone)
library(kableExtra)

source("helper_functions.R")

comp_vars                       <- params$comp_vars
comparator                      <- params$comparator
var_name_to_pretty              <- params$var_name_to_pretty
target_drug                     <- params$target_drug
all.data                        <- params$all.data
```

```{r prepare-vars}

char_vars <- comp_vars[
  sapply(all.data %>% dplyr::select(all_of(comp_vars)), class) == "character"
]

all.data <- all.data %>%
  mutate(across(
    all_of(char_vars), 
    ~as.factor(.)
    ))

fact_vars <- comp_vars[
  sapply(all.data %>% dplyr::select(all_of(comp_vars)), class) == "factor"
]

if(sum(
  sapply(all.data %>% dplyr::select(all_of(fact_vars)), 
         function(x){length(levels(x))}) == 2)
  ){
  warning("Please input 2-level factors as logicals.")
}
```

```{r prepare-labels}
comp_vars_pretty <- data.frame(var_name = comp_vars) %>%
  left_join(var_name_to_pretty, by = "var_name") %>%
  arrange(pretty_var_category, pretty_name)%>%
  mutate(pretty_var_category = if_else(
    pretty_var_category == lag(pretty_var_category),
    "",
    pretty_var_category,
    missing = pretty_var_category
  ))
```

```{r table-spec}
varsToFactor <- comp_vars_pretty$var_name

new_titles <- c("n",
                unlist(
                  lapply(
                    1:nrow(comp_vars_pretty),
                    function(col_num){
                      c(
                        comp_vars_pretty$pretty_var_category[col_num],
                        rep("", length(levels(all.data[[comp_vars_pretty$var_name[col_num]]])))
                        )
                    }
                  ),
                  use.names = FALSE
                )
)

new_names <- c("",
               unlist(
                  lapply(
                    1:nrow(comp_vars_pretty),
                    function(col_num){
                      c(
                        comp_vars_pretty$pretty_name[col_num],
                        levels(all.data[[comp_vars_pretty$var_name[col_num]]])
                        )
                    }
                  ),
                  use.names = FALSE
                )
)
```

```{r tables, results='asis'}
Drug_Population_for_Target_vs_Drug <- paste0(comparator, "_Population_for_", target_drug, "_vs_", comparator)

html <- my_table1(this.data     = all.data,
                  my_strata     = Drug_Population_for_Target_vs_Drug,
                  filename      = paste0(target_drug, "_vs_", comparator, "-Table1"),
                  varsToFactor  = varsToFactor,
                  new_colnames  = c("Variable",
                                    "",
                                    paste0("TOTAL ", target_drug, " vs ", comparator, " Population"),
                                    paste0(target_drug, " Population"),
                                    paste0(comparator, " Population"),
                                    "p"),
                  verbose       = FALSE,
                  new_titles    = new_titles,
                  new_names     = new_names)
cat("\n\n##", target_drug, "vs", comparator, "\n\n")
cat(html)
```
