---
title: "Antidiabetic Drug Overlap"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: flatly
params:
  dte_cohort_data2:   NULL
  all_groups:         NULL
  nontreatment_group: "Nontreatment"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(corrplot)
library(plotrix)
library(libRtheme)

this.data         <- params$dte_cohort_data2
all_groups        <- params$all_groups
nontreatment_group <- params$nontreatment_group
all_drugs         <- all_groups[all_groups != nontreatment_group]
```

```{r precedence-flags}
# Loop over each drug to identify which drug comes first
for (i in 1:length(all_groups)) {
  this_drug_1 <- all_groups[i]
  for (j in 1:length(all_groups)) {
    this_drug_2 <- all_groups[j]
    if (this_drug_1 == this_drug_2) { next }
    var_name_timeline    <- paste0(this_drug_1, "_index_precedes_", this_drug_2, "_index")
    var_name_drug_1_index <- paste0(this_drug_1, "_Index")
    var_name_drug_2_index <- paste0(this_drug_2, "_Index")

    this.data <- this.data %>%
      mutate(!!sym(var_name_timeline) := !!sym(var_name_drug_1_index) < !!sym(var_name_drug_2_index))
  }
}
```

## Lifetime Co-occurrence

```{r co-occurrence-matrix}
use_matrix    <- this.data %>%
  select(paste0(c(all_drugs, nontreatment_group), "_Index")) %>%
  mutate(across(everything(), ~ if_else(is.na(.), 0L, 1L))) %>%
  as.matrix
co_occurrence <- t(use_matrix) %*% use_matrix

axis_titles         <- c(paste0(all_drugs, " Use"), paste0(nontreatment_group, " Group"))
rownames(co_occurrence) <- axis_titles
colnames(co_occurrence) <- axis_titles
```

```{r co-occurrence-plot, fig.width=25, fig.height=20}
par(mar = c(0, 0, 0, 0))

my_palette <- libr.pal(200, "LIBR_gradient_pink")[1:175]

corrplot(co_occurrence,
         is.corr         = FALSE,
         method          = "color",
         addCoef.col     = "transparent",
         number.cex      = 1.2,
         tl.col          = "black",
         tl.cex          = 1.5,
         tl.srt          = 45,
         mar             = c(2, 0, 0, 0),
         cl.pos          = "n",
         col             = my_palette,
         family          = "Poppins")

# mtext("Lifetime Co-occurrence Counts of Antidiabetic Medications",
#       side   = 3,
#       line   = -15,
#       adj    = 0.75,
#       cex    = 2,
#       col    = "black",
#       family = "Poppins")

formatted_numbers <- apply(co_occurrence, c(1, 2), function(x) format(x, big.mark = ",", scientific = FALSE))

n <- ncol(co_occurrence)
for (i in 1:n) {
  for (j in 1:n) {
    text(j, n - i + 1, formatted_numbers[i, j], col = "black", cex = 2, family = "Poppins")
  }
}

ticks       <- seq(0, 55000, by = 5000)
tick_labels <- format(ticks, big.mark = ",", scientific = FALSE)

usr       <- par("usr")
legend_xl <- usr[2] + 0.2
legend_yb <- usr[3] + 0.5
legend_xr <- usr[2] + 0.4
legend_yt <- usr[4] - 3.5

color.legend(legend_xl, legend_yb, legend_xr, legend_yt,
             legend    = tick_labels,
             rect.col  = my_palette,
             gradient  = "y",
             align     = "rb",
             cex       = 1.2,
             family    = "Poppins")
```

## Treatment Precedence

```{r precedence-matrix}
use_matrix          <- matrix(NA, nrow = length(all_groups), ncol = length(all_groups))
rownames(use_matrix) <- 1:length(all_groups)
colnames(use_matrix) <- 1:length(all_groups)

for (i in 1:length(all_groups)) {
  this_drug_1             <- all_groups[i]
  rownames(use_matrix)[i] <- paste0(this_drug_1, " precedes")
  for (j in 1:length(all_groups)) {
    this_drug_2             <- all_groups[j]
    colnames(use_matrix)[j] <- this_drug_2
    if (this_drug_1 == this_drug_2) {
      use_matrix[i, j] <- NA
      next
    }
    use_matrix[i, j] <- this.data %>%
      pull(!!sym(paste0(this_drug_1, "_index_precedes_", this_drug_2, "_index"))) %>%
      sum(na.rm = TRUE)
  }
}
```

```{r precedence-plot, fig.width=25, fig.height=20}
par(mar = c(0, 0, 0, 0))

my_palette <- libr.pal(200, "LIBR_gradient_pink")[1:175]

corrplot(use_matrix,
         is.corr         = FALSE,
         method          = "color",
         addCoef.col     = "transparent",
         number.cex      = 1.2,
         tl.col          = "black",
         tl.cex          = 1.5,
         tl.srt          = 45,
         mar             = c(2, 0, 0, 8),
         cl.pos          = "n",
         col             = my_palette,
         family          = "Poppins")

# mtext("Lifetime Co-occurrence Counts of Antidiabetic Medications",
#       side   = 3,
#       line   = -20,
#       adj    = 0.75,
#       cex    = 2,
#       col    = "black",
#       family = "Poppins")

formatted_numbers <- apply(use_matrix, c(1, 2), function(x) format(x, big.mark = ",", scientific = FALSE))

n <- ncol(use_matrix)
for (i in 1:n) {
  for (j in 1:n) {
    text(j, n - i + 1, formatted_numbers[i, j], col = "black", cex = 2, family = "Poppins")
  }
}

ticks       <- seq(0, 55000, by = 5000)
tick_labels <- format(ticks, big.mark = ",", scientific = FALSE)

usr       <- par("usr")
legend_xl <- usr[2] + 0.2
legend_yb <- usr[3] + 5
legend_xr <- usr[2] + 0.4
legend_yt <- usr[4] - 7.5

color.legend(legend_xl, legend_yb, legend_xr, legend_yt,
             legend    = tick_labels,
             rect.col  = my_palette,
             gradient  = "y",
             align     = "rb",
             cex       = 1.2,
             family    = "Poppins")
```
