---
title: "Eligibility Criteria: `r params$target_drug` Cohorts"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: flatly
params:
  eligibility_inclusion_diagnoses: NULL
  all_drugs:                       NULL
  comparator_groups:               NULL
  var_name_to_pretty:              NULL
  comparator_drugs:                NULL
  target_drug:                     "Semaglutide"
  diagnosis_timeline_filename:         NULL
  nontreat_data_filename:                NULL
  diag_table_filename:                      NULL
  nontreatment_group:              "Nontreatment"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(tableone)
library(kableExtra)

source("helper_functions.R")

eligibility_inclusion_diagnoses <- params$eligibility_inclusion_diagnoses
all_drugs                       <- params$all_drugs
comparator_groups               <- params$comparator_groups
var_name_to_pretty              <- params$var_name_to_pretty
comparator_drugs                <- params$comparator_drugs
target_drug                     <- params$target_drug
nontreatment_group              <- params$nontreatment_group

load(params$diag_table_filename)
load(params$diagnosis_timeline_filename)
loaded_var <- load(params$nontreat_data_filename) # restores named variable
nontreat_data <- get(loaded_var[1])
```

```{r prepare-labels}
eligibility_inclusion_diagnoses_pretty <- data.frame(var_name = eligibility_inclusion_diagnoses) %>%
  left_join(var_name_to_pretty, by = "var_name") %>%
  pull(pretty_name)

all_drugs_pretty <- data.frame(var_name = all_drugs) %>%
  left_join(var_name_to_pretty, by = "var_name") %>%
  pull(pretty_name)

cohort_names <- do.call(c, lapply(
  comparator_groups,
  function(x) {
    c(paste0(target_drug, "_Population_for_", target_drug, "_vs_", x),
      paste0(x, "_Population_for_", target_drug, "_vs_", x))
  }
))
```

```{r build-dataset}
all.data <- nontreat_data %>%
  left_join(diagnosis_timeline_data, by = "PatientDurableKey") %>%
  filter(eval(parse(text = paste(cohort_names, collapse = " | "))))
```

```{r table-spec}
varsToFactor <- c(
  eligibility_inclusion_diagnoses,
  paste0(eligibility_inclusion_diagnoses, "_Before_Drug_Index"),
  paste0(all_drugs, "_Use"),
  paste0(all_drugs, "_Overlaps_Drug_Index")
)

new_titles <- c("n",
                "Diagnoses",
                rep("", length(eligibility_inclusion_diagnoses) - 1),
                "Diagnosis occurs before the index",
                rep("", length(eligibility_inclusion_diagnoses) - 1),
                "Lifetime Use of Drug Treatments",
                rep("", length(all_drugs) - 1),
                "Co-Occuring Treatment Use within 6 months before or 12 months after index",
                rep("", length(all_drugs) - 1)
)

new_names <- c("",
               eligibility_inclusion_diagnoses_pretty,
               eligibility_inclusion_diagnoses_pretty,
               all_drugs_pretty,
               all_drugs_pretty
)
```

```{r tables, results='asis'}
for (this_group in comparator_groups) {

  if (this_group == target_drug) { next }

  Target_Population_for_Target_vs_Drug <- paste0(target_drug, "_Population_for_", target_drug, "_vs_", this_group)
  Drug_Population_for_Target_vs_Drug   <- paste0(this_group, "_Population_for_", target_drug, "_vs_", this_group)

  this.data <- all.data %>%
    filter(!!sym(Target_Population_for_Target_vs_Drug) | !!sym(Drug_Population_for_Target_vs_Drug)) %>%
    mutate(false_col = FALSE)

  for (this_diag in eligibility_inclusion_diagnoses) {
    new_col    <- paste0(this_diag, "_Before_Drug_Index")
    target_col <- paste0(this_diag, "_Before_", target_drug, "_Index")
    other_col  <- paste0(this_diag, "_Before_", this_group, "_Index")

    this.data <- this.data %>%
      mutate(!!new_col := ifelse(!!sym(Target_Population_for_Target_vs_Drug),
                                 !!sym(target_col), !!sym(other_col)))
  }

  for (this_demo_drug in all_drugs) {
    if (this_demo_drug == target_drug) {
      target_col <- paste0(target_drug, "_Use")
    } else {
      target_col <- paste0(this_demo_drug, "_Overlaps_", target_drug, "_Index")
    }
    
    if (this_demo_drug == this_group) {
      other_col  <- paste0(this_demo_drug, "_Use")
    } else if(this_group == nontreatment_group){
      other_col <- "false_col"
    } else {
      other_col  <- paste0(this_demo_drug, "_Overlaps_", this_group, "_Index")
    } 

    new_col <- paste0(this_demo_drug, "_Overlaps_Drug_Index")

    this.data <- this.data %>%
      mutate(!!new_col := ifelse(!!sym(Target_Population_for_Target_vs_Drug),
                                 !!sym(target_col), !!sym(other_col)))
  }

  html <- my_table1(this.data     = this.data,
                    my_strata     = Drug_Population_for_Target_vs_Drug,
                    filename      = paste0(target_drug, "_vs_", this_group, "-Eligibility_Criteria"),
                    varsToFactor  = varsToFactor,
                    new_colnames  = c("Variable",
                                      "",
                                      paste0("TOTAL ", target_drug, " vs ", this_group, " Population"),
                                      paste0(target_drug, " Population"),
                                      paste0(this_group, " Population"),
                                      "p"),
                    verbose       = FALSE,
                    new_titles    = new_titles,
                    new_names     = new_names)
  cat("\n\n##", target_drug, "vs", this_group, "\n\n")
  cat(html)
}
```
