---
title: "Propensity Score Covariate Summary: `r params$target_drug`"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    theme: flatly
params:
  comparator_groups: NULL
  ps_covariates:     NULL
  target_drug:       "Semaglutide"
  output_filename:   "OutputData/PS_Covariates-Summary.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(kableExtra)
```

```{r build-summary}
this_ps_covariates <- params$ps_covariates

for (this_drug in params$comparator_groups) {
  this_ps_cov_list   <- read.csv(paste0("OutputData/PS_Covariates-", this_drug, ".csv"))
  this_ps_covariates <- this_ps_covariates %>%
    mutate(!!sym(this_drug) := var %in% this_ps_cov_list$var)
}

PS_Covariates_summary <- this_ps_covariates %>%
  mutate(sum = rowSums(across(where(is.logical)), na.rm = TRUE)) %>%
  arrange(-sum, across(all_of(params$comparator_groups))) %>%
  dplyr::select(var, all_of(params$comparator_groups))

write.csv(PS_Covariates_summary, params$output_filename, row.names = FALSE)
```

```{r display}
PS_Covariates_summary %>%
  mutate(across(where(is.logical), ~ ifelse(., "X", ""))) %>%
  kbl(col.names = c("Variable", params$comparator_groups)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = TRUE, font_size = 14)
```
